# Railway deployment configuration
version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - PYTHONPATH=/app
    restart: unless-stopped
